package mafgo

// GDCMultipleAlignmentFormat -- a data type that handles GDC MAF files
type GDCMultipleAlignmentFormat struct {
	HugoSymbol                 string
	EntrezGeneID               string
	Center                     string
	NCBIBuild                  string
	Chromosome                 string
	StartPosition              integer
	EndPosition                integer
	Strand                     string
	VariantClassification      string
	VariantType                string
	ReferenceAllele            string
	TumorSeqAllele1            string
	TumorSeqAllele2            string
	dbSNPRS                    string
	dbSNPValStatus             string
	TumorSampleBarcode         string
	MatchedNormSampleBarcode   string
	MatchNormSeqAllele1        string
	MatchNormSeqAllele2        string
	TumorValidationAllele1     string
	TumorValidationAllele2     string
	MatchNormValidationAllele1 string
	MatchNormValidationAllele2 string
	VerificationStatus         string
	ValidationStatus           string
	MutationStatus             string
	SequencingPhase            string
	SequenceSource             string
	ValidationMethod           string
	Score                      string
	BAMFile                    string
	Sequencer                  string
	TumorSampleUUID            string
	MatchedNormSampleUUID      string
	HGVSc                      string
	HGVSp                      string
	HGVSpShort                 string
	TranscriptID               string
	ExonNumber                 string
	tDepth                     string
	tRefCount                  string
	tAltCount                  string
	nDepth                     string
	nRefCount                  string
	nAltCount                  string
	AllEffects                 string
	Allele                     string
	Gene                       string
	Feature                    string
	FeatureType                string
	OneConsequence             string
	Consequence                string
	cDNAPosition               string
	CDSPosition                string
	ProteinPosition            string
	AminoAcids                 string
	Codons                     string
	ExistingVariation          string
	AlleleNum                  string
	Distance                   string
	TranscriptStrand           string
	Symbol                     string
	SymbolSource               string
	HGNCID                     string
	Biotype                    string
	Canonical                  string
	CCDS                       string
	ENSP                       string
	SwissProt                  string
	Trembl                     string
	Uniparc                    string
	RefSeq                     string
	SIFT                       string
	PolyPhen                   string
	Exon                       string
	Intron                     string
	Domains                    string
	GMAF                       string
	AFRMAF                     string
	AMRMAF                     string
	ASNMAF                     string
	EASMAF                     string
	EURMAF                     string
	SASMAF                     string
	AAMAF                      string
	EAMAF                      string
	CLINSIG                    string
	Somatic                    string
	Pubmed                     string
	MotifName                  string
	MotifPos                   string
	HighInfPos                 string
	MotifScoreChange           string
	Impact                     string
	Pick                       string
	VariantClass               string
	TSL                        string
	HGVSOffset                 string
	Pheno                      string
	Minimised                  string
	ExACAF                     string
	ExACAFAdj                  string
	ExACAFAfr                  string
	ExACAFAmr                  string
	ExACAFEas                  string
	ExACAFFin                  string
	ExACAFNfe                  string
	ExACAFOth                  string
	ExACAFSas                  string
	GenePheno                  string
	Filter                     string
	Context                    string
	SrcVcfID                   string
	TumorBamUUID               string
	NormalBamUUID              string
	CaseID                     string
	GDCFilter                  string
	COSMIC                     string
	MC3Overlap                 string
	GDCValidationStatus        string
	GDCValidSomatic            string
	VCFRegion                  string
	VCFInfo                    string
	VCFFormat                  string
	VCFTumorGT                 string
	VCFNormalGT                string
}

// TCGAMultipleAlignmentFormat -- a data type that handles TCGA MAF files
